### PR TITLE
Package the license file

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the license file is packaged in sdists, wheels, and other build products.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @mvdbeek

**Comment by jakirkham** [comment]
Thoughts @pjdelport?

**Comment by PiDelport** [comment]
I'm not sure this is necessary: the `LICENSE` file (and other VCS-tracked files) are already being packaged using `setuptools-scm`, rather than `MANIFEST.in`.

**Comment by jakirkham** [comment]
Ok, so that does seem to be true of `sdist`s, but the `whl`s don't have the license file for some reason. :/

**Comment by PiDelport** [comment]
That should be the norm for Python packaging: the bdists / wheels only include the files that get installed; not all the source files that are in the sdist.

**Comment by jakirkham** [comment]
So I'm just following [this recommendation for wheels]( https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file ).

Should add am happy to drop the `MANIFEST.in` change since you're using `setuptools-scm` and that seems to be working fine.

Does this all sound ok or am I miss some other concerns?

**Comment by jakirkham** [comment]
Have dropped this down to the wheel change. Please let me know what you think.

**Comment by PiDelport** [comment]
Hmm, I don't think we require this, as such: the wheel functionality seems to be there primarily for licenses that require redistributing the license text along with all distributable artifacts, which the Python license doesn't (as far as I know).

On the other, it doesn't hurt, and the`setup.cfg` change is small and non-intrusive, so it should be fine. :)

**Comment by PiDelport** [comment]
Thanks!

**Pull request merged**
