### PR TITLE
Normalize module exports with stdlib

### PR DESCRIPTION
**Pull request by kislyuk**
Pass through all tempfile exports. Hide implementation imports. Add
tests for this behavior.

### CODE REVIEW

**Comment by kislyuk** [comment]
@pjdelport, any updates on this?

I would suggest a more proactive approach to maintenance given that you're maintaining a backport of a stdlib package. I have created a new org, https://github.com/backports, and invited you (currently no one else). Perhaps you would be open to moving backports packages there and adding collaborators, and also giving them PyPI release access? That way the maintenance burden can be shared.

**Comment by PiDelport** [comment]
Apologies, this has been on my list of things to get to!

The @backports team sounds like a good idea, although @jazzband is maybe also maybe worth consideration, as a more established effort with the same umbrella goal?

**Comment by kislyuk** [comment]
Haven't heard of jazzband before but I'm open to participating there, too.
IMHO "backports" has the advantage of being more self-explanatory.

**Comment by PiDelport** [comment]
My apologies for the lack of proper response. (Thanks for pinging me in #2!)

This change has been raised for other backports modules as well, but I think keeping the stdlib namespace separate from the backports one may be the best approach, rather than merging and re-exporting it: see https://github.com/PiDelport/backports.os/issues/10 for a discussion about this.

**Comment by kislyuk** [comment]
OK, thanks for the response @PiDelport. I understand the reasoning.

There is no convention that I could find for whether backports packages should transclude the original package namespace.

If you prefer not to do it, I would suggest that you update the module documentation to include advice to use the following pattern instead of `from backports import tempfile`, for this and other packages that you maintain:

```
try:
    from PACKAGE import NAME
except ImportError:
    from backports.PACKAGE import NAME
```

**Pull request closed without merging**
